routes:
  - id: "My Little Pony #2"
    destination: "http://0.0.0.0:8080/example"
    predicates:
      - type: Path
        path: "/example"
      - type: RemoteAddr
        addrs:
          - 127.0.0.1
    filters:
      - type: AddRequestHeader
        name: "X-Request-Red"
        value: "blue"
      - type: AddRequestParameter
        name: "cool-parameter"
        value: "cool-value"
