server:
  port: 8080

spring:
  application:
    name: your-gateway
  cloud:
    config:
      uri: http://config-server:8888
      failFast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
